/** @fileoverview Curated changelog data for the "What's New" popup, generated from git history. */

export const CHANGELOG = [
  {v:'Unreleased', date:'2026-08-31', current:true, items:[
    ['improved', 'Offloaded the history/timelapse generation to a new thread to prevent lagging the app out when rendering'],
    ['improved', 'Improved the performance of the pattern tool as well as blur algorithms. Added a toggle to turn off history/snapshot recording to reduce lag'],
    ['fixed', 'Fixed an issue with pattern tool rendering not masking properly with the user strokes in some circumstances'],
    ['fixed', 'Fixed an issue with users uploading with the wrong name to the gallery and allowed upload privilege to unregistered users'],
    ['fixed', 'Fixed an issue where you could not kick users that timed out/ghost users'],
    ['fixed', 'Fixed an issue where chat would expand when hovered over while drawing a stroke'],
    ['improved', 'Improved the admin UI, added an account reset and search bar'],
    ['added', 'Implemented changelog overlay that appears with each update'],
  ], more:[
    ['improved', 'Improved chat layout and collapse as well as limited the preview size of image messages when the chat is minified'],
    ['fixed', 'Fixed an issue with chat scrolling snapping back to the bottom'],
    ['fixed', 'Fixed a minor bug with replays being cut off if the board size is changed mid-replay'],
    ['added', 'Added ctrl+space as a default colour switch shortcut for the app'],
    ['improved', 'Improved saving from selection by adding a bit of padding to the image'],
    ['improved', 'Selection lasso is now hidden while a user is saving via selection'],
    ['fixed', 'Fixed overlapping UI when pressure is disabled'],
  ], moreTotal:7},
  {v:'v1.13.2-beta', date:'2026-08-30', items:[
    ['added', 'Added a few new groupings for image brush images and fixed a bug with pattern brush not loading the new images properly'],
    ['improved', 'Improved tool option slider UI'],
    ['improved', 'Improved eraser performance'],
    ['improved', 'Improved eraser rendering by using a simple preview for layer 1 erasing operations'],
    ['improved', 'Improved tag handling when uploading images to the gallery'],
    ['improved', 'Improved the sync UI'],
    ['added', 'Added functionality to setting/clearing the snapshot that is served when a user first joins the room'],
    ['fixed', 'Fixed a minor bug with brush rendering and improved the tool options UI'],
  ], more:[
    ['fixed', 'Fixed a minor sync UI bug'],
    ['improved', 'Syncing now populates the history window with the synced history for scrubbing through'],
    ['improved', 'Improved the toolbar collapse on small devices'],
    ['fixed', 'Fixed a few minor bugs in the tutorial sequence'],
  ], moreTotal:4},
  {v:'v1.13.0-beta', date:'2026-08-23', items:[
    ['improved', 'Improved the tool options sliders and toolbar UI to maximize space'],
    ['improved', 'Improved layer preview visibility'],
    ['added', 'Added keybinds 1-8 for custom preset brushes'],
    ['improved', 'Improved chat transition animations when changing sizes'],
    ['improved', 'Improved frame rendering algorithms to improve performance for low-end machines'],
    ['fixed', 'Fixed a build bug and improved canvas rendering to reduce lag'],
    ['fixed', 'Fixed a few bugs with moderation'],
    ['improved', 'Improved some of the colour palette UI'],
  ], more:[
    ['improved', 'Improved the colour presets UI'],
    ['fixed', 'Fixed broken build for release'],
    ['fixed', 'Fixed an issue where certain settings would not apply properly'],
    ['improved', 'Performance testing WIP'],
  ], moreTotal:4},
  {v:'v1.12.3-beta', date:'2026-08-18', items:[
    ['added', 'Implemented new custom brush images and improved timelapse rendering on the gallery'],
    ['added', 'Added some new fonts and improved text tool UI a bit'],
    ['improved', 'Reworked the old snapshot history to use the new .ddraw file format'],
    ['added', 'Implemented right click options for various tools'],
    ['improved', 'Improved tutorial text/clarity and implemented chat country flags'],
    ['improved', 'Improved some board rendering algorithms to reduce lag'],
    ['fixed', 'Fixed an issue with changing timelapse crop in the gallery'],
    ['fixed', 'Fixed an issue with syncing selection masks'],
  ], more:[
    ['fixed', 'Fixed an issue with selection masks not appearing in the history properly'],
    ['improved', 'Improved timelapse editing UI'],
    ['improved', 'Improved the .ddraw compression algorithm'],
    ['improved', 'Tweaked the webpage styling and fixed some gallery attributions'],
    ['fixed', 'Fixed an issue with the resync UI when coming back from being AFK'],
    ['fixed', 'Fixed some UI layering issues'],
    ['fixed', 'Fixed a minor issue with selection fill not being cleared entirely when moved, leaving a ring of pixels on the board'],
  ], moreTotal:7},
  {v:'v1.12.2-beta', date:'2026-08-13', items:[
    ['added', 'Implemented a toggle for unbounded warp - homography transforms that can extend beyond the bounding box of the selection'],
    ['improved', 'Improved site login and fixed issues with tablets not being able to click certain dialog buttons'],
    ['fixed', 'Fixed some bugs with selection not being replayed properly'],
    ['fixed', 'Fixed a sequencing issue with undo from tablet users causing the wrong strokes to be undone'],
    ['improved', 'Tweaked the auto-timelapse editing for gallery uploads - BETA'],
    ['improved', 'Improved the palette UI to no longer be tied to board coordinates'],
    ['fixed', 'Fixed an issue with the previous board loading not appearing properly in the current history panel'],
  ], more:[
  ], moreTotal:0},
  {v:'v1.12.1-beta', date:'2026-08-12', items:[
    ['added', 'Implemented gallery timelapse controls and increased the automatic timelapse framerate while reducing its resolution'],
    ['fixed', 'Fixed an issue with selection transforms lagging when distorted very large'],
    ['improved', 'Improved the snapshot auto-loading and added it as a room setting'],
    ['improved', 'Tweaked gallery UI'],
  ], more:[
  ], moreTotal:0},
  {v:'v1.12.0-beta', date:'2026-08-11', items:[
    ['improved', 'Improved UI on some tool buttons for legibility'],
    ['improved', 'Improved the stroke baking sync between users, fixing potential issues with mis-matched undo order'],
    ['fixed', 'Fixed minor issue with new selection sequencing within the replay system'],
    ['fixed', 'Fixed confetti stamping  issue'],
    ['fixed', 'Fixed issues with syncing not replicating a users\' own strokes properly'],
    ['improved', 'Updated landing UI for better embed'],
    ['improved', 'Release beta v1.12.0'],
  ], more:[
  ], moreTotal:0},
  {v:'v1.11.0-beta', date:'2026-07-15', items:[
    ['improved', 'Refactored some code involving chat, colour and the new replay system'],
    ['improved', 'Improved timelapse rendering for gallery preview and fixed some bugs related to the new replay system'],
    ['improved', 'Improved the UI of the main page, gallery and messenger'],
    ['improved', 'Improved the save UI and chat UI'],
    ['improved', 'Improved mobile layout menus and chat controls'],
    ['added', 'Implemented custom gold name for supporters'],
    ['added', 'Implemented proper mobile scaling'],
    ['fixed', 'Fixed some minor issues with replay UI and rendering not using the start/end time properly'],
  ], more:[
    ['improved', 'Main UI Tweaks and release v1.11.0-beta'],
  ], moreTotal:1},
  {v:'v1.10.3-beta', date:'2026-06-28', items:[
    ['fixed', 'Fixed some minor issues with gallery connection'],
    ['fixed', 'Fixed a minor issue with a popup appearing too soon'],
  ], more:[
  ], moreTotal:0},
  {v:'v1.10.2-beta', date:'2026-06-28', items:[
    ['added', 'Added tutorial for new replay system'],
    ['added', 'Implemented new badges to display next to your username'],
    ['fixed', 'Fixed the new replay/recording system not functioning properly in an offline room'],
    ['added', 'Implemented timelapse uploading on the gallery'],
    ['added', 'Added transparent rendering for image sequences from replays'],
    ['improved', 'Improved the UI for image brush and fixed readability of some buttons'],
    ['fixed', 'Fixed an env error that broke the gallery upload'],
    ['fixed', 'Fixed an issue with pattern not rendering properly in replays/sync'],
  ], more:[
    ['improved', 'Improved the rendering UI, added better feedback for when an upload completes'],
    ['fixed', 'Fixed an issue with the selection clearing covering up existing strokes and not showing up properly in the replay'],
    ['fixed', 'Fixed an issue with the replay overlay not resizing properly when the room has a different board size than the replay\'s board size'],
    ['improved', 'Improved the handling of window resizing so the view doesn\'t change as much'],
    ['fixed', 'Fixed some pattern image scaling and pattern menu UI'],
    ['improved', 'Tweaked the tutorial UI'],
  ], moreTotal:6},
  {v:'v1.10.1-beta', date:'2026-06-16', items:[
    ['improved', 'Improved the new replay system UI and added a start/end time for rendering recordings out'],
    ['fixed', 'Fixed a rendering/lag issue with the replay system scrubbing large replay files'],
    ['improved', 'Tweaked the automatic sizing for tool options, improved the custom brush gallery UI'],
    ['improved', 'Tweaked how homography transformations and flipping interact with the selection tool'],
    ['added', 'Added snapshot layers to prevent edge cases where replays could not undo/redo properly directly after a snapshot'],
    ['improved', 'Improved replay options and functionality'],
    ['improved', 'Improved replay UI to be consistent between the live replay and the recording window'],
    ['improved', 'Reworked messenger encryption, removed duplicate code from messenger & select tool, consolidated rate limiting to one file'],
  ], more:[
    ['fixed', 'Fixed an issue with blend modes not applying properly in the replay for the glitch bruish'],
    ['fixed', 'Fixed an issue with the confetti brush opacity setting not working'],
    ['fixed', 'Fixed an issue with undo not working properly with glitch brush results'],
    ['fixed', 'Fixed some issues with undo ordering not working properly when syncing'],
    ['fixed', 'Fixed an issue with blend modes not rendering correctly in some instances of the replay as well as glitch blur functionality when it comes to blend mode strokes'],
    ['fixed', 'Fixed an issue with erasers flickering while multiple users are drawing, implemented some sync testing files'],
    ['improved', 'Cleaned up old sync provider/election code, server now holds the sync data'],
    ['fixed', 'Fixed a desync issue caused by background tab throttling'],
    ['improved', 'Automated cleanup of old testing code and legacy code'],
    ['improved', 'Simplified duplicate code'],
  ], moreTotal:10},
  {v:'v1.10.0-beta', date:'2026-06-09', items:[
    ['improved', 'Improved replay scrubbing renderer, fixed opacity issue with eraser tool'],
    ['fixed', 'Fixed an issue with recently uploaded images remaining on the board for new users'],
    ['fixed', 'Fixed an issue with undo and blend modes when syncing'],
    ['fixed', 'Fixed some issues with blend modes, undo/redo and snapshot caching for the improved sync'],
    ['improved', 'Improved the replay UI and fixed some issues with image manipulation and mirror not being represented properly'],
    ['fixed', 'Fixed an issue with the volume slider in the chat UI'],
    ['fixed', 'Fixed some scaling issues with the select tool UI'],
    ['improved', 'Improved socket limits, added missing db indexes and some duplicate code'],
  ], more:[
    ['improved', 'Improved new replay system when handling undos to prevent discontinuity, fixed minor bugs with late joining users not undoing properly'],
    ['fixed', 'Fixed an issue with join messages not displaying the proper rank'],
    ['improved', 'Continued working on sync improvements, fixed race condition with the automatic login'],
    ['fixed', 'Fixed an issue with eraser rendering breaking active stroke blend modes'],
    ['fixed', 'Fixed an issue with advanced fill rendering improperly'],
    ['improved', 'Replaced history menu with 2 minute local replay recording'],
    ['improved', 'Completed automated replay testing'],
    ['fixed', 'Fixed an issue with room settings button appearing incorrectly and room settings not being transferred from temporary room state to registered room state'],
    ['improved', 'Finished testing sync overhaul, fixed minor bug with doubled initial dot in preview stroke'],
    ['removed', 'Disabled advanced fill on the mirror and fixed confetti preview stroke not rendering in the mirror'],
    ['fixed', 'Fixed a minor issue with cursors being rendered when they should be hidden on join'],
    ['fixed', 'Fixed minor issue where users would not see their own badge rendered'],
    ['removed', 'Removed empty space in replay recordings, fixed minor cursor issue'],
  ], moreTotal:13},
  {v:'v1.9.2-beta', date:'2026-05-25', items:[
    ['fixed', 'Fixed some sync issues, git release v1.9.2-beta'],
  ], more:[
  ], moreTotal:0},
  {v:'v1.9.1-beta', date:'2026-05-24', items:[
    ['added', 'Added new gallery format WIP'],
    ['added', 'Implemented preliminary replay system'],
    ['improved', 'Improved replay system UI and functionality, added a video export option'],
    ['added', 'Implemented layer merging by region'],
    ['added', 'Added title input and tag username option to gallery upload'],
    ['added', 'Implemented PWA functionality for the ddraw.ca/go url'],
    ['improved', 'Improved IPv6 handling for moderation purposes'],
    ['improved', 'Improved the moderation UI'],
  ], more:[
    ['added', 'Implemented tweakable local snapshot settings'],
    ['improved', 'Improved gallery pagination with numbered page buttons'],
    ['improved', 'Improved gallery appearance and functionality, tweaked app UI, added profile status'],
    ['fixed', 'Fixed an issue with blur tool overlapping weirdly for remote users'],
    ['fixed', 'Fixed selection merge for remote users'],
    ['fixed', 'Fixed IPv6 subnet ban matching'],
    ['fixed', 'Fixed blend mode preview layer order'],
    ['fixed', 'Fixed fill preview layer order'],
    ['fixed', 'Fixed glitch blur layer sync'],
    ['fixed', 'Fixed discord badge not appearing next to users in the user list on the tauri app and implemented new badge system for future use'],
    ['improved', 'Tweaked chat UI slightly, added volume bar to chat'],
    ['fixed', 'Fixed some bugs with multi-dimensional animated gimp brushes'],
    ['fixed', 'Fixed a bug with preview strokes not rendering properly'],
    ['fixed', 'Fixed ink thinning preview toggle'],
    ['fixed', 'Fixed left sidebar floating controls'],
    ['removed', 'Removed staff chat empty message'],
    ['fixed', 'Fixed snapshot uploader names'],
    ['improved', 'Improved landing page'],
    ['fixed', 'Fixed a bug in the gimp parsing code'],
    ['fixed', 'Fixed some issues with discord bot messaging and versioning'],
  ], moreTotal:20},
  {v:'v1.9.0-beta', date:'2026-05-18', items:[
    ['fixed', 'Fixed some issues with auth and improved tutorial on smaller screens'],
    ['fixed', 'Fixed an issue with user cursors not disappearing during disconnection'],
  ], more:[
  ], moreTotal:0},
  {v:'v1.8.4-beta', date:'2026-05-16', items:[
    ['added', 'Implemented vanishing vector text tool mode'],
    ['fixed', 'Fixed an issue with the auto updater and chat notification sounds'],
    ['improved', 'Improved global message style'],
    ['fixed', 'Fixed an issue with board size not being updated properly'],
    ['fixed', 'Fixed an issue with users being stuck in room'],
  ], more:[
  ], moreTotal:0},
  {v:'v1.8.3-beta', date:'2026-05-14', items:[
    ['added', 'Added new advanced tools tutorial and improved pattern/image brush UI'],
    ['fixed', 'Fixed some issues related to rate limiting and improved confetti brush rendering'],
    ['improved', 'Tweaked confetti UI'],
    ['fixed', 'Fixed a minor issue with the join button and tweaked stroke preview UI to be less intrusive'],
  ], more:[
  ], moreTotal:0},
  {v:'v1.8.0-beta', date:'2026-05-13', items:[
    ['added', 'Added some new options for the confetti brush'],
    ['added', 'Implemented Discord login and account merging with existing DDraw accounts. Implemented basic discord bot code'],
    ['fixed', 'Fixed an issue with auto-login not working consistently and tweaked landing page UI'],
    ['fixed', 'Fixed some bugs with discord login on tauri app'],
    ['improved', 'Made the new colour palettes nice rectangles'],
    ['fixed', 'fixed minor bugs with eraser, blur tool and glitch blur'],
    ['improved', 'Improved profile UI, added stats, fixed minor issues with Discord login'],
    ['removed', 'Removed old version checking loop'],
  ], more:[
    ['fixed', 'Fixed some minor UI bugs'],
  ], moreTotal:1},
  {v:'v1.7.2-beta', date:'2026-05-12', items:[
    ['added', 'Added selection tool tutorial'],
    ['added', 'Added proper gallery URLs for profiles'],
    ['fixed', 'Fixed an issue with the new brush preview not rendering properly'],
    ['added', 'Added new floating colour palettes, fixed an issue with layers not undoing while using tablet'],
    ['fixed', 'Fixed an issue with the new Existing pixels type blend mode not rendering properly'],
    ['added', 'Implemented email verification and password resets'],
    ['fixed', 'Fixed an issue with new colour palette toggling and movement'],
    ['fixed', 'Fixed an issue with the undo button not working locally'],
  ], more:[
    ['fixed', 'Fixed an issue with undo not working on some layers'],
    ['fixed', 'Fixed an issue with sync performing slowly and not showing the correct layer/stroke counts'],
    ['fixed', 'Fixed an edge case of sycing while another user is drawing'],
    ['fixed', 'Fixed a minor issue with ctrl+backspace in the text tool'],
    ['improved', 'Caches floating gallery images on the server as they will be sent to each user that connects'],
  ], moreTotal:5},
  {v:'v1.7.1-beta', date:'2026-05-09', items:[
    ['fixed', 'Fixed an issue with the rendering of the classic brush'],
    ['fixed', 'Fixed an issue with fluid brush not rendering properly in the mirror mode'],
    ['fixed', 'Fixed an issue with the Existing blend mode rendering with increased opacity on the preview stroke'],
    ['fixed', 'Fixed some minor issues with auto-updater'],
  ], more:[
  ], moreTotal:0},
  {v:'v1.7.0-beta', date:'2026-05-09', items:[
    ['added', 'Added a new confetti brush, alongside a new brush stroke preview and tweaked the tutorial popup'],
    ['added', 'Added a new tutorial overlay and tweaked the ranking system'],
    ['added', 'Added bg colour to board viewer and fixed lag with popout board viewer'],
    ['added', 'Added new obscure button on select tool menu for trusted users and up to hide NSFW art on the board'],
    ['added', 'Added vercel analytics hooks for getting page load time data'],
    ['fixed', 'Fixed the new obscure region UI'],
    ['fixed', 'Fixed an issue with pressure controlling glitch brush opacity'],
    ['fixed', 'Fixed an issue with preview stroke layer not being cleared on mouseup'],
  ], more:[
    ['fixed', 'Fixed the mask region not appearing when a user joins the room'],
    ['fixed', 'Fixed an issue with the auto updater not prompting users to refresh in the browser'],
    ['fixed', 'Fixed an issue of users not seeing another user\'s currently loaded image for image brushes'],
    ['improved', 'Tweaked app packaging so the landing page loads more quickly'],
    ['fixed', 'Fixed an issue with remote users not rendering preview strokes properly underneath higher layers'],
    ['improved', 'Tweaked the admin panel UI'],
    ['removed', 'Removed low latency refresh as it caused flickering issues'],
  ], moreTotal:7},
  {v:'v1.6.4-beta', date:'2026-05-05', items:[
    ['added', 'Implemented a new selection mask for only affecting selected pixels'],
    ['added', 'Added scroll to zoom option in the settings'],
    ['fixed', 'Fixed an issue with all layer eraser preview and rendering for remote users'],
    ['fixed', 'Fixed an issue with fluid brush flickering while being drawn'],
    ['improved', 'Major refactor and code cleanup'],
    ['fixed', 'Fixed some issues with flickering strokes'],
    ['fixed', 'Fixed an issue with touch input on the board not focusing the app window'],
    ['fixed', 'Fixed an issue with doubled opacity when applying blend modes over existing pixels'],
  ], more:[
    ['improved', 'Tweaked sidebar UI scaling'],
  ], moreTotal:1},
  {v:'v1.6.3-beta', date:'2026-05-03', items:[
    ['fixed', 'Fixed an issue with auto-update not prompting the user to update/refresh the page once the new server is up'],
    ['fixed', 'Fixed an issue with chat styling'],
    ['fixed', 'Fixed the history button not working w/ certain inputs and the group UI swapping tool positions'],
    ['improved', 'Tweaked auto-updater and new release code'],
    ['fixed', 'Fixed board viewer not showing correct bg colour'],
    ['fixed', 'Fixed an issue with blend modes not appearing properly in the active stroke layers'],
    ['fixed', 'Fixed an issue with blur/glitch blur not applying to the room\'s background colour properly'],
    ['improved', 'Tweaked the styling on the topbar'],
  ], more:[
  ], moreTotal:0},
  {v:'v1.6.2-beta', date:'2026-05-03', items:[
    ['improved', 'Overhauled the likes system on the gallery'],
    ['added', 'Added new weighted slider mode for size and a +/- button for tool option fine control'],
    ['added', 'Implemented content aware selection scaling to remove excess empty pixels from the current selection'],
    ['fixed', 'Fixed an issue with re-rendering tool UI while drawing'],
    ['fixed', 'Fixed an issue with select tool not syncing properly'],
    ['fixed', 'Fixed some issues with select tool UI and resizing of sidebar sections'],
    ['fixed', 'Fixed lag involving the board view rendering and zooming'],
    ['fixed', 'Fixed an issue with the draw offline feature continually prompting the user when the server updates'],
  ], more:[
    ['fixed', 'Fixed an issue with glitch blur rendering and undo'],
    ['fixed', 'Fixed an issue with likes not counting correctly in the gallery'],
    ['fixed', 'Fixed an issue with eraser in radial mirror modes'],
    ['fixed', 'Fixed an issue with the sync provider not being replaced  even if they become inactive'],
    ['fixed', 'Fixed image size handling when uploading to the brush/pattern gallery'],
    ['fixed', 'Fixed an issue with the chat not showing user enter/leave events correctly'],
    ['fixed', 'Fixed an issue with mirror region re-rendering glitch blur for all stamps'],
    ['improved', 'Tweaked chat styling to work better mobile devices'],
    ['improved', 'Cleaned up the new mini colour wheel code'],
    ['fixed', 'Fixed scaling issue with pattern brush and added multi-image uploading'],
    ['improved', 'Reworked eraser rendering method'],
    ['fixed', 'Fixed an issue with lag caused by linear scaling of images still using complex homography transforms'],
    ['fixed', 'Fixed an issue with inactivity being stuck in a loop when returning'],
    ['fixed', 'Fixed some buttons not working with tablet input'],
    ['fixed', 'Fixed some svelte build warnings'],
    ['fixed', 'Fixed the mini colour wheel not resizing properly'],
    ['fixed', 'Fixed an issue with cursor appearing on the board when changing sizes'],
    ['improved', 'Tweaked the app landing page UI to be a bit cleaner and more mobile friendly'],
    ['added', 'Added small colour picker for mobile users'],
    ['improved', 'Updated IP masking rules for mods'],
    ['improved', 'Tweaked user dropdown menu to include the username'],
    ['improved', 'Tweaked the UI and app sliders'],
    ['improved', 'Tweaked the main page for SEO purposes, added 404 page'],
    ['improved', 'Tweaked the custom cursors'],
    ['improved', 'Tweaked glitch blur fallback'],
    ['improved', 'Tweaked permissions'],
    ['improved', 'Tweaked app UI for mobile and added new mini-colour wheel that pops up on small screen devices'],
    ['fixed', 'Fixed a couple minor UI issues with the app landing page'],
  ], moreTotal:28},
  {v:'v1.6.1-beta', date:'2026-04-29', items:[
    ['fixed', 'Fixed an issue with fluid brush not interpolating properly for remote users'],
    ['fixed', 'Fixed a weird bug with chat rendering with huge gaps'],
  ], more:[
  ], moreTotal:0},
  {v:'v1.6.0-beta', date:'2026-04-29', items:[
    ['added', 'Added a new confirmation popup and tweaked full-screen uploaded images'],
    ['added', 'Added a blend mode lock and set it to lock selection and blur tools to normal by default'],
    ['added', 'Implemented a cursor rAF optimization'],
    ['fixed', 'Fixed an issue with the pattern brush rendering causing lag'],
    ['fixed', 'Fixed an issue with fluid brush rendering jagged'],
    ['improved', 'Tweaked blend modes to work with the board background colour properly and select tool'],
    ['fixed', 'Fixed a minor bug with sync using the circle blur tool'],
    ['fixed', 'Fixed an issue with local snapshots not working on the browser'],
  ], more:[
    ['fixed', 'Fixed the upload button on the tauri app which was not working'],
    ['fixed', 'Fixed an issue with ghost users appearing as previously connected users'],
    ['fixed', 'Fixed an issue with tablets clicking on recent colours'],
    ['improved', 'Tweaked the auto-update to not run instantly without user input'],
    ['fixed', 'Fixed a couple UI issues'],
    ['improved', 'Tweaked server snapshots to show Loading... while loading thumbnails'],
    ['improved', 'Tweaked the testing files to work with updated delta-based packet bundles'],
    ['improved', 'Tweaked cursor name colour slightly'],
    ['improved', 'Tweaked the landing page UI'],
    ['improved', 'Re-implemented background functioning blend modes'],
    ['fixed', 'Fixed a minor bug with blend modes'],
  ], moreTotal:11},
  {v:'v1.5.6-beta', date:'2026-04-26', items:[
    ['added', 'Added user colour option to the image brush'],
    ['fixed', 'Fixed an issue with the app not loading gallery images correctly'],
    ['fixed', 'Fixed an issue with undo/redo buttons not appearing correctly'],
    ['fixed', 'Fixed an issue with sync providers not syncing when afk'],
    ['fixed', 'Fixed an issue with rendering ink brush strokes'],
    ['fixed', 'Fixed an issue with undo/redo error'],
    ['fixed', 'Fixed some issue with the pattern brush gallery UI'],
    ['improved', 'Tweaked local snapshot system to allow for uploading to the board'],
  ], more:[
    ['fixed', 'Fixed an issue with spacing tool setting being shown as a long floating point number'],
    ['improved', 'Tweaked styling of image brush ui'],
    ['fixed', 'Fixed an issue with the updater popping up multiple times after updating'],
    ['fixed', 'Fixed some issues with tablet not working on some UI elements'],
    ['improved', 'Replaced tool options <input> tags with custom svelte components for better tablet input handling'],
    ['fixed', 'Fixed an issue with sliders not updating properly'],
    ['fixed', 'Fixed a minor issue with new tool option sliders not rendering the lines properly'],
    ['improved', 'Tweaked slider colour slightly'],
    ['improved', 'Optimized the board view renderer'],
    ['improved', 'Made usernames more visible on the board with an invert filter'],
    ['fixed', 'Fixed a minor bug with undoing current selection'],
    ['improved', 'Moved the location of snapshot folders as it was not working properly on the db'],
    ['fixed', 'Fixed some minor issues with brush sync between users'],
    ['improved', 'Tweaked UI'],
  ], moreTotal:14},
  {v:'v1.5.5-beta', date:'2026-04-25', items:[
    ['fixed', 'Fixed some issues with lag related to rendering cursors and new recently active checks for sorting the userlist'],
  ], more:[
  ], moreTotal:0},
  {v:'v1.5.3-beta', date:'2026-04-25', items:[
    ['added', 'Added new userlist sorting method: recently active'],
    ['added', 'Added a failsafe if a sync layer gets stuck'],
    ['added', 'Implemented @user messages in the chat'],
    ['added', 'Added toggle to disable board view'],
    ['fixed', 'Fixed an issue with the likes counter on the floating gallery images when selected'],
    ['fixed', 'Fixed an issue with sync causes users to be rate-limited'],
    ['added', 'Added a /messenger/ page on the website to act as a place to DM users without loading the entire app'],
    ['added', 'Added custom updater UI'],
  ], more:[
    ['improved', 'Tweaked ink brush rendering to remove random dots'],
    ['fixed', 'Fixed an issue with rank colours not appearing properly in the popout chat window on the tauri app'],
    ['fixed', 'fixed an issue with update popups occuring on server close not start'],
    ['fixed', 'Fixed an issue with svg elements not being rendered smoothly'],
    ['fixed', 'Fixed an issue with refreshing the tauri app not reloading the page properly'],
    ['fixed', 'Fixed an issue with ranks being misattributed when users leave/rejoin the room'],
    ['fixed', 'Fixed an issue w messenger not working on dev server'],
    ['improved', 'Active strokes are now merged onto main layers when a user becomes afk'],
    ['fixed', 'Fixed minor issue with updater showing download instead of refresh in browser'],
    ['fixed', 'Fixed a minor issue with global messaging'],
  ], moreTotal:10},
  {v:'v1.5.0-beta', date:'2026-04-24', items:[
    ['added', 'Added new floating gallery that surrounds room board'],
    ['fixed', 'Fixed an issue with undo operations and the selection tool'],
    ['added', 'Added new room sizes'],
    ['fixed', 'Fixed bugs involving new room sizes and floating gallery'],
    ['added', 'Added custom bg colour local override'],
    ['added', 'Added a fix for region-restore not working for inactive users causing desync'],
    ['fixed', 'Fixed issues with classic brush rendering'],
    ['fixed', 'Fixed an issue with blend modes causing a white bg on layer 1'],
  ], more:[
    ['fixed', 'Fixed an issue with image manipulation and selection desync for inactive tabs'],
    ['fixed', 'Fixed an issue with focus being stuck on the chat when returning to draw with a tablet, breaking shortcuts'],
    ['fixed', 'Fixed mirror region not scaling properly'],
    ['fixed', 'Fixed colour updating in the app settings'],
    ['fixed', 'Fixed an issue with blurry text/usernames'],
    ['fixed', 'Fixed an issue with glitchblur preview lagging during long strokes'],
    ['fixed', 'Fixed an issue with the auto updater prompt'],
    ['improved', 'Updated versioning notes for 1.4.3-beta'],
    ['fixed', 'Fixed an issue with snapshots not loading properly and made a snapshot extraction python script'],
    ['improved', 'Changed blend mode rendering to ignore transparent pixels'],
    ['improved', 'Changed board size option as 4k was a bit too large'],
    ['improved', 'Cleaned up debug'],
  ], moreTotal:12},
  {v:'v1.4.3-beta', date:'2026-04-23', items:[
    ['fixed', 'Fixed sync for ink brush'],
    ['fixed', 'Fixed an issue with fluid pen rendering improperly for remote users'],
  ], more:[
  ], moreTotal:0},
  {v:'v1.4.2-beta', date:'2026-04-23', items:[
    ['added', 'Implemented skeleton for password reset logic'],
    ['fixed', 'Fixed an issue with point reduction not working on fluid brush'],
    ['fixed', 'Fixed a bug with the server restoring the board automatically'],
    ['fixed', 'Fixed an issue with joining an empty room not connecting immediately'],
  ], more:[
  ], moreTotal:0},
  {v:'v1.4.1-beta', date:'2026-04-22', items:[
    ['added', 'Added new update warnings before server reset and global message system'],
    ['added', 'Added linking to specific gallery posts'],
    ['added', 'Added esc as a shortcut for closing windows/chat'],
    ['added', 'Added some chat sound effects'],
    ['added', 'Added a local board flipping button'],
    ['added', 'Added a confirmation for the clear button'],
    ['fixed', 'Fixed an issue with stamping tools causing lag'],
    ['fixed', 'Fixed an issue with gallery links in the chat not working'],
  ], more:[
    ['fixed', 'Fixed an issue with inconsistencies in the pattern brush stroke between users'],
    ['fixed', 'Fixed an issue with ink brush re-rendering full screen for remote users'],
    ['fixed', 'Fixed an issue with smoothness of the fluid brush'],
    ['fixed', 'Fixed join message not appaering for some users and username not appearing in sync menu'],
    ['improved', 'Changed default chat opacity to 95%'],
    ['improved', 'Updated rendering path for stamp-based brush to prevent unnecessary redraws'],
    ['fixed', 'Fixed an issue with ink/fluid brush rendering re-rendering the whole canvas instead of just the affected regions'],
    ['fixed', 'Fixed a few more optimizations with remote user rendering'],
    ['fixed', 'Fixed inactive state not being rendered properly in the userlist'],
    ['fixed', 'Fixed a bug with the auto-updater'],
    ['fixed', 'Fixed an issue with blur/glitch blur stamping not being correct between users'],
    ['fixed', 'Fixed an issue with obfuscating IPv6 properly'],
    ['fixed', 'Fixed an issue with hardness not mirroring properly'],
    ['fixed', 'Fixed an issue with inactivity timer not working properly'],
    ['fixed', 'Fixed position of board viewer button on tauri app'],
    ['improved', 'Tweaked room description so it doesn\'t escape its bounds in the room list'],
    ['improved', 'Tweaked the styling of the board viewer'],
    ['improved', 'Tweaked font slightly on the app landing page'],
    ['improved', 'Tweaked inactivity to compress a users\' active strokes to main layers after 5 minutes'],
    ['removed', 'Removed some server functionality from local hosting'],
    ['fixed', 'Fixed a minor bug with UI visibility in the moderation menu'],
    ['removed', 'Disabled the join button when a user is not connected to the server'],
    ['improved', 'Updated version notes'],
    ['improved', 'Optimized compositor rendering to use dirtyrect sized drawImage calls wherever possible'],
    ['improved', 'Preliminary email verification'],
    ['fixed', 'Fixed some minor issues with UI on small width devices'],
  ], moreTotal:26},
  {v:'v1.3.4-beta', date:'2026-04-22', items:[
    ['added', 'Added user metrics for use with steam achievements in the future'],
  ], more:[
  ], moreTotal:0},
  {v:'v1.3.3-beta', date:'2026-04-21', items:[
    ['added', 'Added custom tool presets w/ keybinds 1-6'],
    ['fixed', 'Fixed an issue with the select tool lag'],
    ['added', 'Added custom preset highlight when selected and added shift+click to lock/unlock all locks on a tool'],
    ['added', 'Added a new board viewer function that allows you to have a secondary board view active and pop it out into a new window'],
    ['fixed', 'Fixed an issue with changing sizes during strokes not being synced between users'],
    ['improved', 'Tweaked styling of board viewer'],
    ['fixed', 'Fixed minor desyncs in the ending points of fluid and ink brush'],
    ['fixed', 'Fixed minor bug with inkdropper and alt+tabbing apps keeping the inkdropper selected'],
  ], more:[
    ['fixed', 'Fixed a minor issue with auto-update display'],
  ], moreTotal:1},
  {v:'v1.3.2-beta', date:'2026-04-21', items:[
    ['added', 'Added new bandwidth probe to find the best sync provider'],
    ['fixed', 'Fixed an issue with input delay on tool options when using tablet'],
    ['added', 'Added finer controls to advanced fill expansion/blur'],
    ['added', 'Added low-latency setting to test implemetation of \'desynchronized\' hint on canvases'],
    ['fixed', 'Fixed some errors in the console regarding chat'],
    ['fixed', 'Fixed some issues with sync and user indentification'],
    ['fixed', 'Fixed inactive status for users who are just using the chat'],
    ['improved', 'Tweaked the app upload feature to prevent a powershell terminal from popping up'],
  ], more:[
    ['added', 'Implemented getCoalescedEvents for more precise drawing and improved point reduction algorithm to remove redundant points'],
    ['improved', 'Tweaked the sync to show who you are syncing to'],
    ['improved', 'Tweaked updater and added feedback when uploading to gallery'],
    ['fixed', 'Fixed an issue with app bundle size'],
    ['fixed', 'Fixed an issue with reconnecting putting users in room \'default\''],
    ['improved', 'Reduced packet size for ink and fluid brush'],
    ['fixed', 'Fixed an issue with rate limiting causing some strokes w/ pressure to not be fully sent'],
    ['fixed', 'Fixed an issue with dragging the topbar in the tauri app'],
    ['fixed', 'Fixed an issue with opacity being applied twice for some tools'],
    ['fixed', 'Fixed a bug with point reduction affecting pre-determined image stamp distances'],
    ['fixed', 'Fixed an issue with pattern fill and with flickering when commiting strokes'],
    ['fixed', 'Fixed an issue with local rendering of ink strokes not using the same points as remote users'],
    ['improved', 'Tweaked notes'],
    ['improved', 'Recovered some branches lost in merging'],
    ['fixed', 'Fixed minor bugs in the tauri auto-updater UI'],
    ['fixed', 'Fixed an issue with moving small selections'],
  ], moreTotal:16},
  {v:'v1.3.0-beta', date:'2026-04-19', items:[
    ['added', 'Added a new grid overlay for use with the pixel brush for use at high zooms ( > 500% )'],
    ['added', 'Implemented multiline text in the tool, allowed ctrl+z while using text tool'],
    ['fixed', 'Fixed a bug with fill tool and mirror regions'],
    ['added', 'Added a cursor selection for brush/eraser and tweaked chat styling'],
    ['fixed', 'Fixed gallery like system'],
    ['fixed', 'Fixed an issue with the select cursor not disappearing when swapping to text tool'],
    ['improved', 'Improved the image and pattern brush selection menu to allow for custom images'],
    ['improved', 'Restored gallery hearts from previous voting system'],
  ], more:[
    ['fixed', 'Fixed an issue with selection re-rendering the full board when filling'],
    ['fixed', 'Fixed an issue with login attempts'],
    ['fixed', 'Fixed an issue with pattern brush not initializing properly for remote users'],
    ['improved', 'Tweaked gallery style and made the icons look nicer'],
    ['improved', 'Tweaked the rendering method of the pattern brush to use a brush stroke mask'],
    ['fixed', 'Fixed windows tauri update runner'],
    ['fixed', 'Fixed download link on main page'],
    ['fixed', 'Fixed some warnings in the build'],
    ['fixed', 'Fixed remote api base for desktop version checking'],
    ['fixed', 'Fixed an issue with local cursor disappearing/not rendering properly'],
    ['fixed', 'Fixed a bug with hardness being too much on brushes'],
    ['fixed', 'Fixed an issue with desync on inactive tabs when a user swaps fonts'],
    ['fixed', 'Fixed an error with versioning'],
    ['fixed', 'Fixed an issue with the cursor disappearing on the app'],
    ['fixed', 'Fixed an issue with the app not dragging properly when moving it from fullscreen/maximized'],
    ['fixed', 'Fixed an issue with text not rendering properly for inactive tabs'],
    ['fixed', 'Fixed text-wrapping on long usernames on the board'],
    ['improved', 'Updated the version dialog so users can still draw offline with an out-dated client'],
    ['improved', 'Tweaked snapshot behaviour when joining a room with users already in it'],
    ['improved', 'updated minRequired version in version.json'],
    ['improved', 'Tweaked the snapshot loading popup that appears when you rejoin a room alone'],
    ['fixed', 'Fixed an issue with the pattern being enabled for fill and select simultaneously instead of independently'],
    ['improved', 'Updated installer to 1.2.3-beta'],
    ['improved', 'Tweaked the app title and added link back to landing page'],
    ['improved', 'Updated download links'],
    ['fixed', 'Fixed pixel brush not rendering properly for remote users at a small size'],
    ['improved', 'Initial protocol buffer optimizations'],
    ['fixed', 'Fix circle blur opacity inconsistency for inactive tabs'],
    ['fixed', 'Fix circle blur opacity reducing on repeated stamps'],
    ['improved', 'Force composite on inactive tabs before circle blur sampling'],
    ['improved', 'Batch circle blur compositing to prevent progressive color shifts'],
    ['fixed', 'Fix circle blur sampling to use stroke-start snapshot'],
    ['removed', 'Removed room persistence for unregistered rooms'],
    ['fixed', 'Fixed minor issue w/ inkdropper consistency'],
    ['fixed', 'Fixed a minor issue with focus when using dropdowns'],
  ], moreTotal:35},
  {v:'v1.0.0-beta and earlier', date:'2026-04-17', note:'Initial build-out — core drawing, sync, tools', items:[
    ['added', 'Added a basic board sync feature'],
    ['added', 'Implemented new ink brush type'],
    ['added', 'Added undo/redo buttons, pan and rotation tool'],
    ['added', 'Added stamping distance to the blur and circle blur tool to help reduce lag'],
    ['added', 'Implemented new layer/blend mode system'],
    ['added', 'Implemented pixel brush as a new brush mode'],
    ['added', 'Implemented redo and undo in the replay system'],
    ['added', 'Added a recording button to start the replay system'],
  ], more:[
    ['added', 'Added tags to images and a new comments/tags section in the gallery'],
    ['added', 'Added a new moderation tab to the room settings menu'],
    ['added', 'added new updated stress tests, reduced undo limit to 10'],
    ['added', 'Implemented a limit to the catch-up input buffer while using the replay system. Forces a sync now after a certain time threshold'],
    ['added', 'Added inkdropper tool and rgb/hsv/hex menu'],
    ['added', 'Implemented blur tool and circle-blur tool.'],
    ['added', 'Added text tool support for touch users'],
    ['improved', 'Improved smoothing algorithm and applied it to the eraser and image brush tool'],
    ['added', 'Implemented tool-grouping collapse for the tool bar if the height is too short'],
    ['added', 'Implemented room management system, room description and room ownership'],
    ['added', 'Implemented new debug panel'],
    ['added', 'Implemented a basic flood fill tool'],
    ['added', 'Implemented pattern mode on the fill tool'],
    ['added', 'Implemented pattern fill for the select tool'],
    ['added', 'Added a bunch of new svg images and fixed the messenger sever connection'],
    ['added', 'Added a few new icon images'],
    ['added', 'Added and implemented some new icons'],
    ['added', 'Added a room preview system'],
    ['added', 'Added new svg brushes and patterns'],
    ['added', 'Added resizable sections to the tool options'],
    ['added', 'Added 3 new fonts to the text tool'],
    ['added', 'Implemented image uploading and system tray icon for windows app; added a few new icons'],
    ['added', 'Implemented build system and auto updates for Tauri app'],
    ['added', 'Implemented new right-click zoom method, zoom tool and hotkeys associated'],
    ['added', 'Added Trusted rank into the system properly'],
    ['added', 'Added colour swatches for primary/secondary and a new hex text box'],
    ['added', 'Added a new keybind for swapping between primary/secondary colours: X'],
    ['added', 'Added hardness option for tools and tool option lock to maintain values on selected tools while swapping'],
    ['added', 'Implemented lasso selection mode'],
    ['added', 'Implemented moderation and mongodb basics'],
    ['fixed', 'Fixed bugs with selection tool and ink brush'],
    ['improved', 'Refactoring in progress, created shared folder for functions used by server and client. Consolidated homography functions into homographyUtils.js for selection. Separated the input buffer array into InputBufferManager.js. Created KeyboardHandler.js for future keybindings. And various other drawing/tool related functions have been isolated into their own files'],
    ['added', 'Implemented undo, tweaking blend modes/layers functionality'],
    ['added', 'Implemented layers and blend modes, alongside an undo/redo functionality'],
    ['fixed', 'Fixed selection tool copy/paste leaving a white background'],
    ['fixed', 'Fixed some bugs with selection tool for remote users'],
    ['fixed', 'Fixed an issue with sync in the new layer system'],
    ['added', 'Added pressure-size preview inside main brush when using a tablet'],
    ['added', 'Implemented dirty rect math to reduce layer calculation costs'],
    ['fixed', 'Fixed an error with the selection tool and compositing when user leaves room'],
    ['added', 'Implemented collapsable sidebar and resizable undo/redo button'],
    ['added', 'Implemented a new tool option thinning to control the velocity based pressure of the ink tool'],
    ['fixed', 'Fixed a bug with the text tool and shortcuts and a bug with the image brush preview'],
    ['added', 'Added mirrored fill/advanced fill and mirrored selection fill/clear'],
    ['added', 'Implemented dirty rect tiles and wasm worker for findcontent function in layer manager'],
    ['added', 'Implemented and connected gallery, changed room URLs slightly'],
    ['added', 'Implemented all layer select mode'],
    ['fixed', 'Fixed the glitch implementation in the replay system'],
    ['fixed', 'Fixed the circle blur tool in the replay system'],
    ['added', 'Implemented remote user viewing of pattern brush and pattern fill. WIP'],
    ['fixed', 'Fixed pattern brush in the replay system'],
    ['fixed', 'Fixed doubled opacity with the replay system and also the fill tool'],
  ], moreTotal:569},
];
