/**
 * InputBufferManager - Manages input buffering, tick loop, smoothing, and point reduction
 * Runs at 90 TPS to process input data and broadcast to server
 */

import { douglasPeucker, distanceBasedCulling } from './utils/drawing.js';

export class InputBufferManager {
  constructor(app) {
    this.app = app;

    // Tick loop configuration
    this.tickRate = 90; // TPS (ticks per second)
    this.tickInterval = 1000 / this.tickRate; // ~11.11ms
    this.tickTimer = null;
    this.lastTickTime = null;

    // Input buffer for accumulating pointer events between ticks
    this.inputBuffer = {
      points: [],        // Flat array: [x1, y1, x2, y2, ...]
      pressure: 1,       // Current pressure (0-1)
      pointerType: 'mouse',
      position: null,    // Latest { x, y }
      lastPosition: null, // Previous { x, y }
      movement: { x: 0, y: 0 }, // Accumulated delta for panning
      dirty: false       // True if new data since last tick
    };

    // Point reduction configuration (Level 1: bandwidth optimization)
    this.pointReduction = {
      enabled: true,
      algorithm: 'douglas-peucker', // 'douglas-peucker' or 'distance-based'
      // Douglas-Peucker parameters (epsilon range)
      minEpsilon: 0.1,
      maxEpsilon: 2.0,
      // Distance-based parameters
      minDistance: 1,
      maxDistance: 5
    };

    // Baseline smoothing configuration
    this.baselineSmoothing = {
      pointReduction: {
        minEpsilon: 0.5,
        maxEpsilon: 2.0
      }
    };

    // Broadcast smoothing buffer (matches tool smoothing for sync)
    this.broadcastSmoothBuffer = { x: 0, y: 0, isFirst: true };
  }

  startTickLoop() {
    if (this.tickTimer) return; // Already running

    this.lastTickTime = performance.now();
    this.tickTimer = setInterval(() => this.tick(), this.tickInterval);
  }

  stopTickLoop() {
    if (this.tickTimer) {
      clearInterval(this.tickTimer);
      this.tickTimer = null;
    }
  }

  tick() {
    const now = performance.now();
    this.lastTickTime = now;

    const { app } = this;

    // Skip local drawing while syncing
    if (app.syncClient?.isSyncing()) return;

    // Only process if we have new input data OR need to catch up smoothing
    const needsCatchup = this.needsSmoothingCatchup();
    if (!this.inputBuffer.dirty && !needsCatchup) return;

    const { points, movement } = this.inputBuffer;

    // Handle panning movement
    if (app.self.panning && app.self.mousedown && (movement.x !== 0 || movement.y !== 0)) {
      app.board.pan(movement.x, movement.y);
      this.inputBuffer.movement = { x: 0, y: 0 }; // Reset accumulated movement
    }

    // Process drawing if we have position data
    if (points.length >= 2) {
      // 1. Calculate broadcast points early (before local processing)
      let broadcastPoints;
      if (app.self.mousedown && !app.self.panning) {
        broadcastPoints = this.applyBroadcastSmoothing(points);
        broadcastPoints = this.applyPointReduction(broadcastPoints);
      } else {
        broadcastPoints = points;
      }

      // For blur tools, use the reduced broadcast points for local processing too
      // This ensures local and remote users process the same points (perfect sync)
      const blurTools = ['blur', 'circleBlur'];
      const localPoints = (app.self.mousedown && !app.self.panning && blurTools.includes(app.self.tool))
        ? broadcastPoints
        : points;

      // 2. Update self state with the LATEST point in the batch
      const lastX = localPoints[localPoints.length - 2];
      const lastY = localPoints[localPoints.length - 1];
      app.self.setPosition(lastX, lastY);

      // 3. Process locally for immediate feedback (must run before broadcast for flowPen stamp buffer)
      if (app.self.mousedown && !app.self.panning) {
        const tool = app.toolManager.getCurrentTool();
        if (tool) {
          // We iterate through the batch locally so the user sees smooth lines
          // For blur tools, we use reduced points to match what remote users will see
          for (let i = 0; i < localPoints.length; i += 2) {
              const currentPos = { x: localPoints[i], y: localPoints[i+1] };
              const prevPos = i === 0 ? (this.inputBuffer.lastPosition || currentPos) : { x: localPoints[i-2], y: localPoints[i-1] };
              tool.onPointerMove(app.self, currentPos, prevPos);

              // Debug: Track each point processed locally
              app.debugOverlay.addStrokePoint(app.self.id, currentPos.x, currentPos.y, 'tick');
          }
        }
      }

      // 4. Broadcast to remote users
      if (app.self.tool === 'flowPen' && app.self.mousedown && !app.self.panning) {
        // FlowPen: send exact stamp positions (already generated by tool.onPointerMove above)
        const tool = app.toolManager.getCurrentTool();
        const { ps: stampPs, rs: stampRs } = tool.drainStampBuffer();
        if (stampPs.length > 0) {
          app.wsClient.broadcastStampMove(stampPs, stampRs);
        }
      } else if (app.self.tool === 'ink' && app.self.mousedown && !app.self.panning) {
        // Ink: send raw points + pressures via rs field
        const tool = app.toolManager.getCurrentTool();
        const { ps: fhPs, rs: fhRs } = tool.drainPointBuffer();
        if (fhPs.length > 0) {
          app.wsClient.broadcastStampMove(fhPs, fhRs);
        }
      } else {
        // Use pre-calculated broadcastPoints
        if (broadcastPoints.length > 0) {
          app.wsClient.broadcastMove(broadcastPoints);
        }
      }

      this.inputBuffer.lastPosition = { x: lastX, y: lastY };
    }

    // Smoothing catch-up: continue drawing towards target even when pointer is still
    if (needsCatchup) {
      this.processSmoothingCatchup();
    }

    // Clear points for next tick
    this.inputBuffer.points = [];
    this.inputBuffer.dirty = false;
  }

  /**
   * Check if smoothing needs to catch up to the target position
   * @returns {boolean} - True if catch-up is needed
   */
  needsSmoothingCatchup() {
    const { app } = this;

    // Only catch up when actively drawing (not panning, mouse is down)
    if (!app.self.mousedown || app.self.panning) return false;

    const tool = app.toolManager.getCurrentTool();
    if (!tool || !tool.smoothBuffer) return false;

    // Only catch up for tools that use EMA smoothing (not ink - it uses its own streamline)
    const smoothingTools = ['brush', 'flowPen'];
    if (!smoothingTools.includes(app.self.tool)) return false;

    // Check if smoothing is enabled
    if (!app.self.smoothing || app.self.smoothing === 0) return false;

    // Calculate distance from smoothed position to target
    const dx = app.self.x - tool.smoothBuffer.x;
    const dy = app.self.y - tool.smoothBuffer.y;
    const distance = Math.sqrt(dx * dx + dy * dy);

    // Need catch-up if distance > 1 pixel
    return distance > 1;
  }

  /**
   * Process smoothing catch-up to continue drawing towards target
   */
  processSmoothingCatchup() {
    const { app } = this;
    const tool = app.toolManager.getCurrentTool();
    if (!tool || !tool.smoothBuffer) return;

    // Calculate distance to determine catch-up speed
    const dx = app.self.x - tool.smoothBuffer.x;
    const dy = app.self.y - tool.smoothBuffer.y;
    const distance = Math.sqrt(dx * dx + dy * dy);

    // Scale catch-up iterations based on distance for faster convergence
    // Farther away = more iterations per tick
    let iterations = 1;
    if (distance > 100) iterations = 8;
    else if (distance > 50) iterations = 5;
    else if (distance > 20) iterations = 3;
    else if (distance > 10) iterations = 2;

    // Generate a synthetic pointer move towards the target
    const targetPos = { x: app.self.x, y: app.self.y };
    let prevPos = { x: tool.smoothBuffer.x, y: tool.smoothBuffer.y };

    // Process multiple catch-up steps for faster convergence
    for (let i = 0; i < iterations; i++) {
      tool.onPointerMove(app.self, targetPos, prevPos);
      prevPos = { x: tool.smoothBuffer.x, y: tool.smoothBuffer.y };

      // Check if we've converged (within 1 pixel)
      const dx = app.self.x - tool.smoothBuffer.x;
      const dy = app.self.y - tool.smoothBuffer.y;
      if (Math.sqrt(dx * dx + dy * dy) <= 1) break;
    }

    // Broadcast the final catch-up position
    if (app.self.tool === 'flowPen') {
      const { ps: stampPs, rs: stampRs } = tool.drainStampBuffer();
      if (stampPs.length > 0) {
        app.wsClient.broadcastStampMove(stampPs, stampRs);
      }
    } else {
      const points = [targetPos.x, targetPos.y];
      const broadcastPoints = this.applyBroadcastSmoothing(points);
      const reducedPoints = this.applyPointReduction(broadcastPoints);
      app.wsClient.broadcastMove(reducedPoints);
    }

    // Track for debug overlay
    app.debugOverlay.addStrokePoint(app.self.id, targetPos.x, targetPos.y, 'catchup');
    app.debugOverlay.addDrawingPoint(targetPos.x, targetPos.y, app.self.size, app.self.id);
    app.regionTracker.addDrawingPoint(targetPos.x, targetPos.y, app.self.size, app.self.id);
  }

  /**
   * Apply Level 1 point reduction to reduce bandwidth before network broadcast
   * @param {Array} points - Flat array [x1, y1, x2, y2, ...]
   * @returns {Array} - Reduced flat array
   */
  applyPointReduction(points) {
    // Skip reduction if disabled or insufficient points
    if (!this.pointReduction.enabled || points.length < 4) {
      return points;
    }

    const userSmoothing = this.app.self.smoothing * 100; // Convert 0-1 to 0-100
    const baseline = this.baselineSmoothing.pointReduction;

    // Convert flat array [x1, y1, x2, y2, ...] to point objects
    const pointObjects = [];
    for (let i = 0; i < points.length; i += 2) {
      pointObjects.push({ x: points[i], y: points[i + 1] });
    }

    let reduced;

    if (this.pointReduction.algorithm === 'douglas-peucker') {
      // Always apply at least baseline reduction, scale up with user smoothing
      const epsilon = baseline.minEpsilon +
        (baseline.maxEpsilon - baseline.minEpsilon) * (userSmoothing / 100);

      reduced = douglasPeucker(pointObjects, epsilon);
    } else if (this.pointReduction.algorithm === 'distance-based') {
      // Calculate distance threshold based on smoothing level
      const { minDistance, maxDistance } = this.pointReduction;
      const threshold = minDistance + (maxDistance - minDistance) * (userSmoothing / 100);

      reduced = distanceBasedCulling(pointObjects, threshold);
    } else {
      // Invalid algorithm, return original
      console.warn(`Invalid point reduction algorithm: ${this.pointReduction.algorithm}`);
      return points;
    }

    // Convert back to flat array
    const result = [];
    for (const p of reduced) {
      result.push(p.x, p.y);
    }

    return result;
  }

  /**
   * Apply EMA smoothing to points before broadcast
   * This must match BrushTool.smoothPosition() exactly so remote users
   * see the smoothed position (with lag), not the raw cursor position
   * @param {Array} points - Flat array [x1, y1, x2, y2, ...]
   * @returns {Array} - Smoothed flat array
   */
  applyBroadcastSmoothing(points) {
    if (points.length < 2) {
      return points;
    }

    // Match BrushTool.smoothPosition() formula exactly:
    // totalSmoothing = baseline + userSmoothing * (1 - baseline)
    // factor = 1 - totalSmoothing * 0.9
    const baselineEma = 0.12;
    const userSmoothing = this.app.self.smoothing || 0;
    const totalSmoothing = baselineEma + userSmoothing * (1 - baselineEma);
    const factor = 1 - totalSmoothing * 0.9;

    const result = [];

    for (let i = 0; i < points.length; i += 2) {
      if (this.broadcastSmoothBuffer.isFirst) {
        this.broadcastSmoothBuffer.x = points[i];
        this.broadcastSmoothBuffer.y = points[i + 1];
        this.broadcastSmoothBuffer.isFirst = false;
      } else {
        this.broadcastSmoothBuffer.x += (points[i] - this.broadcastSmoothBuffer.x) * factor;
        this.broadcastSmoothBuffer.y += (points[i + 1] - this.broadcastSmoothBuffer.y) * factor;
      }
      result.push(this.broadcastSmoothBuffer.x, this.broadcastSmoothBuffer.y);
    }
    return result;
  }

  resetBroadcastSmoothing() {
    this.broadcastSmoothBuffer.isFirst = true;
  }
}
